### PR TITLE
Targeting netstandard2.0, net45, net40

### PR DESCRIPTION
**Pull request by mwhelan**
First cut at netstandard2.0 support. with multi-targeting for .Net 4.5 and .Net 4.0 also
- Removed PublicApiGenerator and commented out the one test that uses it
- Couldn't get tests working with .Net 4.0

Everything compiles and all the tests pass.

### CODE REVIEW

**Comment by JosephWoodward** [comment]
Nice! What's stopping you targeting a lower version of the .NET Standard out of interest?

**Comment by mwhelan** [comment]
Naivety probably! :-) What do you recommend? 

The main issue preventing us porting before now was AutoFixture not having been ported so netstandard2.0 helped with that.

**Comment by JosephWoodward** [comment]
AutoFixture not supporting .NET Standard has been a thorn in the side of a few projects. Luckily it looks like the port [has almost been completed](https://github.com/AutoFixture/AutoFixture/pull/773), and judging by the pull request it looks like it'll target .NET Standard 1.5, so there's scope to drop the target down to 1.5 once it's eventually released, in the meantime netstandard 2.0 is the next best thing.

**Comment by JosephWoodward** [comment]
Looks like AutoFixture .NET Core changes have been merged and ready for release in v4 which is good news.

**Comment by robdmoore** [comment]
Sweet!

--
Rob Moore | Readify Principal Consultant, Technical Specialist (Microsoft Azure) | m +61 400 777 763 | e rob.moore@readify.net | w readify.net

**Comment by mwhelan** [comment]
Good to know, thanks!

**Comment by JosephWoodward** [comment]
Probably worth merging this then targeting lower .NET Standard versions in a separate pull request.

**Comment by JosephWoodward** [comment]
Any idea when we can get this merged ([I see AutoFixture 4 RC1 has now been released](https://github.com/AutoFixture/AutoFixture/wiki/v4.0-Release-Notes#%EF%B8%8F-added-net-core-support))

**Comment by luk355** [comment]
AutoFixture v4 is now stable. Whats missing in this PR to get merged, @mwhelan? 

Due to namespace changes in AutoFixture v4, its hard to consume this package together with latest version of AutoFixture.

Happy to help to with any outstanding work.

**Pull request closed without merging**
