### PR TITLE
BuildByConstructor implementation

### PR DESCRIPTION
**Pull request by Bringer128**
Added an implementation to build the object via its constructor with the most parameters. Should address https://github.com/TestStack/TestStack.Dossier/issues/24

### CODE REVIEW

**Comment by Bringer128** [comment]
Locally all of the List tests appear to be failing; I don't have access to the CI server to see if it excludes those tests, but the test I added passes correctly.

If I get time I can look into why the List tests are failing, but they were failing before this pull request.

**Comment by robdmoore** [comment]
It's ok I know why they are failing and can fix it.

you can see the CI server btw - you just have to log in as guest

We're going to pull in your implementation in a slightly different way as part of another PR at some point soon because it ties in nicely with something else we were trying to achieve (nice timing!)

**Comment by Bringer128** [comment]
Sweet, I'll close this off pull request then :)

**Comment by robdmoore** [comment]
This PR was merged as part of #34

**Pull request closed without merging**
